### ISSUE TITLE
Unit test execution

### ISSUE THREAD

**Issue by MikeEdgar** [strimzi/test-container#109]
This may already be on your radar, but I just want to mention that the unit tests do not appear to be running in the CI:

```
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ strimzi-test-container ---
[INFO] Surefire report directory: /home/vsts/work/1/s/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

I didn't see the surefire plugin defined in the POM, so that is probably the issue.

**Comment by see-quick** [comment]
> This may already be on your radar, but I just want to mention that the unit tests do not appear to be running in the CI:
> 
> ```
> [INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ strimzi-test-container ---
> [INFO] Surefire report directory: /home/vsts/work/1/s/target/surefire-reports
> 
> -------------------------------------------------------
>  T E S T S
> -------------------------------------------------------
> 
> Results :
> 
> Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
> ```
> 
> I didn't see the surefire plugin defined in the POM, so that is probably the issue.

Thanks for pointing it out. I think we were running them within integration tests in the past. I have added the surefire plugin [1] and also modified our Azure CI so now we would run UTs and ITs separately. 

[1] - https://github.com/strimzi/test-container/pull/110
