### ISSUE TITLE
Code checks old brokerId when changin it in KRaft mode

### ISSUE THREAD

**Issue by fedinskiy** [strimzi/test-container#124]
When I am running a container in KRaft mode I am also setting up a custom brokerid. Since version 0.108.0 it also requires to set up a nodeId. When I set up both[1],  the method fails with `IllegalState `broker.id` and `node.id` must have same value!`, and when I don't, it fails with `java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.nodeId" is null`.

It seem the problem is in method `withBrokerId` ([source](https://github.com/strimzi/test-container/blob/main/src/main/java/io/strimzi/test/container/StrimziKafkaContainer.java#L656C1-L663C6)), which checks broker id **before** this id is about to change and has no null pointer check on nodeid. This check was added in [this PR](https://github.com/strimzi/test-container/pull/89): despite kraft mode working fine in 0.107.0

[1]
```
  .withNodeId(1)
                .withKraft()
                .withBrokerId(1)
```

**Comment by see-quick** [comment]
Thanks. That's a problem and I think we should let `withBrokerId(...)` be simply just builder option without any validations because then it could lead to these `order-dependent configuration`. In this case (for now) I think you can be fine with just:
```java
  .withBrokerId(1)
  ```
  because AFAIK I am setting it (at least in 0.109.0 version).
  ``java
  if (this.nodeId == null) {
            LOGGER.warn("Node ID is not set. Using broker ID {} as the default node ID.", this.brokerId);
            this.nodeId = this.brokerId;
        }
```
and such validation should be done in the `doStart()` method to avoid this order-depedent configuration.

**Comment by fedinskiy** [comment]
@see-quick I am preparing a fix right now, is the check should be in `doStart` or in `containerIsStarting`? You set nodeId in the latter, so it will make sense to do the check there as well

**Comment by see-quick** [comment]
> @see-quick I am preparing a fix right now, is the check should be in doStart or in containerIsStarting? You set nodeId in the latter, so it will make sense to do the check there as well

Yeah in `containerIsStarting` it makes more sense to have that validation.
